# Generated by Django 4.2.10 on 2024-02-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='None', max_length=32, null=True, unique=True, verbose_name='势力')),
            ],
        ),
        migrations.CreateModel(
            name='Role_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(blank=True, default='None', max_length=32, null=True, verbose_name='武将名称')),
                ('rolecountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randrole.country_table', to_field='country')),
            ],
        ),
    ]
