# Generated by Django 4.2.10 on 2024-02-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randrole', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_table',
            name='rolecountry',
        ),
    ]
