# Generated by Django 4.2.10 on 2024-02-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randrole', '0002_remove_role_table_rolecountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Set_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(blank=True, default='None', max_length=32, null=True, verbose_name='武将名称')),
            ],
        ),
        migrations.CreateModel(
            name='Roleset_Detail_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randrole.role_table')),
                ('setid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randrole.role_set_table')),
            ],
        ),
    ]
