# Generated by Django 4.2.10 on 2024-02-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0003_role_set_table_roleset_detail_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_table',
            name='rolename',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, unique=True, verbose_name='武将名称'),
        ),
        migrations.CreateModel(
            name='Tmp_Role_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgs.role_table', to_field='rolename')),
            ],
        ),
    ]
