# Generated by Django 4.2.10 on 2024-02-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0004_alter_role_table_rolename_tmp_role_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmp_role_table',
            name='role',
        ),
        migrations.AddField(
            model_name='tmp_role_table',
            name='roleid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sgs.role_table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role_table',
            name='rolename',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, verbose_name='武将名称'),
        ),
    ]
