# Generated by Django 4.2.10 on 2024-02-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0006_role_set_table_introduction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role_Set_Table',
            new_name='Set_Table',
        ),
    ]
