# Generated by Django 4.2.10 on 2024-03-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0007_rename_role_set_table_set_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randseed', models.CharField(blank=True, default='None', max_length=256, null=True, verbose_name='随机种子')),
                ('playernum', models.IntegerField(blank=True, default='None', null=True, verbose_name='玩家人数')),
                ('player_states', models.IntegerField(blank=True, default='None', null=True, verbose_name='玩家存活情况')),
            ],
        ),
    ]
