# Generated by Django 4.2.10 on 2024-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0008_table_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, default='None', max_length=10, null=True, verbose_name='技能名称')),
                ('skill_belong', models.CharField(blank=True, default='None', max_length=64, null=True, verbose_name='所属武将')),
                ('skill_server', models.CharField(blank=True, default='None', max_length=32, null=True, verbose_name='属于服务器')),
                ('skill_type', models.CharField(blank=True, default='None', max_length=128, null=True, verbose_name='技能类型')),
                ('skill_detail', models.CharField(blank=True, default='None', max_length=1024, null=True, verbose_name='技能描述')),
            ],
        ),
    ]
