# Generated by Django 4.2.10 on 2024-05-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0009_skills_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_table',
            name='rolecountry',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, unique=True, verbose_name='势力'),
        ),
        migrations.AddField(
            model_name='role_table',
            name='rolegender',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, unique=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='role_table',
            name='roleserver',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, unique=True, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='skills_table',
            name='skill_detail',
            field=models.CharField(blank=True, default='None', max_length=1023, null=True, verbose_name='技能描述'),
        ),
        migrations.AlterField(
            model_name='skills_table',
            name='skill_server',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, verbose_name='所属服务器'),
        ),
    ]
