# Generated by Django 4.2.10 on 2024-05-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0011_alter_role_table_rolecountry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country_Table',
        ),
    ]
