# Generated by Django 4.2.10 on 2024-05-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0012_delete_country_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_table',
            name='rolecountry',
        ),
        migrations.AddField(
            model_name='role_table',
            name='rolecountrys',
            field=models.CharField(blank=True, default='None', max_length=32, null=True, verbose_name='势力'),
        ),
    ]
