# Generated by Django 4.2.10 on 2024-05-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgs', '0013_remove_role_table_rolecountry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role_table',
            old_name='rolecountrys',
            new_name='rolecountry',
        ),
    ]
